import type { NewActivity } from "./db/schema";

// Seed-aktiviteter kuraterade från reference/-PPT:erna:
// Hemmaprogram, HiddenGems, Bilutflykter, Ungdomarna, Elin 50.
// Budget är EUR per person. lat/lng är ungefärliga kartnålar,
// null där platsen är oklar eller utspridd.

export const SEED_ACTIVITIES: NewActivity[] = [
  // ── Hemmaprogram: utan bil, tram/cykel/till fots från huset ──
  {
    title: "Place de la Comédie",
    description:
      "Montpelliers levande huvudtorg, 'L'Œuf'. Gatumusiker, fontänen Trois Grâces, terrasser och Operan. Utgångspunkt för gamla stan. Tram 1 direkt från huset, ca 20 min.",
    category: "kultur",
    tags: ["utan bil", "gratis", "centrum"],
    budgetMin: 0,
    budgetMax: 5,
    durationMin: 240,
    address: "Place de la Comédie, Montpellier",
    lat: 43.6086,
    lng: 3.8794,
    addedBy: "Andreas",
  },
  {
    title: "Vandring i Écusson",
    description:
      "Gamla stans krångliga gränder, gömda torg och hôtels particuliers. Helt bilfritt, många skuggiga gator. Sikta på Place Saint-Roch och Place de la Canourgue; Rue de l'Aiguillerie och Rue de l'Ancien Courrier är finaste shoppinggatorna.",
    category: "kultur",
    tags: ["utan bil", "gratis", "promenad"],
    budgetMin: 0,
    budgetMax: 10,
    durationMin: 180,
    address: "Écusson, Montpellier",
    lat: 43.611,
    lng: 3.874,
    addedBy: "Andreas",
  },
  {
    title: "Promenade du Peyrou",
    description:
      "Storslagen 1700-talsterrass med utsikt mot akvedukten och vid klart väder Pyrenéerna. Triumfbåge, vattenpaviljong, stora gräsplaner för picknick. Solnedgången härifrån är värd att sikta på.",
    category: "utflykt",
    tags: ["utan bil", "gratis", "solnedgång", "picknick"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 90,
    address: "Place Royale du Peyrou, Montpellier",
    lat: 43.611,
    lng: 3.87,
    addedBy: "Andreas",
  },
  {
    title: "Jardin des Plantes",
    description:
      "Frankrikes äldsta botaniska trädgård (1593), 2 600 arter, skuggiga alléer och dammar. Lugn oas, gratis. Stänger lunchtid på sommaren — kolla öppettider. 5 min från Peyrou.",
    category: "utflykt",
    tags: ["utan bil", "gratis", "skugga"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 120,
    address: "Boulevard Henri IV, Montpellier",
    lat: 43.614,
    lng: 3.873,
    addedBy: "Andreas",
  },
  {
    title: "Halles Castellane",
    description:
      "Klassisk täckt saluhall från 1855: ost, charkuterier, fisk, och bardiskar där man äter lunch med ett glas vin. Kom före kl 13, stängt måndagar. Köp med ost och pâté hem till middagen.",
    category: "mat",
    tags: ["utan bil", "lunch", "saluhall"],
    budgetMin: 12,
    budgetMax: 18,
    durationMin: 90,
    address: "Rue de la Loge, Montpellier",
    lat: 43.6106,
    lng: 3.8757,
    addedBy: "Andreas",
  },
  {
    title: "Antigone-distriktet",
    description:
      "Ricardo Bofills postmoderna 80-talskvarter i pastell, ner till Lez-floden och Pont Juvénal. Fotogeniskt och helt annorlunda mot Écusson. Bäst tidigt eller sent pga värmen; simhallen Olympic Antigone ligger här.",
    category: "kultur",
    tags: ["utan bil", "gratis", "arkitektur"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 90,
    address: "Antigone, Montpellier",
    lat: 43.608,
    lng: 3.888,
    addedBy: "Andreas",
  },
  {
    title: "Musée Fabre",
    description:
      "Ett av Frankrikes främsta konstmuseer utanför Paris: Courbet, Delacroix, Bazille, Soulages. Luftkonditionerat — perfekt stekhet eftermiddag. EU-medborgare under 26 gratis (ta med ID). Stängt måndagar.",
    category: "kultur",
    tags: ["utan bil", "inomhus", "konst"],
    budgetMin: 0,
    budgetMax: 9,
    durationMin: 150,
    address: "39 Boulevard Bonne Nouvelle, Montpellier",
    lat: 43.6113,
    lng: 3.8801,
    addedBy: "Andreas",
  },
  {
    title: "Palavas-les-Flots — stranddag utan bil",
    description:
      "Långa sandstränder, lite kitschig kuststad med glasstånd och fiskebåtar. Tram 3 till Pérols + buss 131, eller cykla Lez-vägen (~10 km). Ta med solskydd och parasoll — lite skugga.",
    category: "strand",
    tags: ["utan bil", "bad", "heldag"],
    budgetMin: 4,
    budgetMax: 20,
    durationMin: 420,
    address: "Palavas-les-Flots",
    lat: 43.528,
    lng: 3.929,
    addedBy: "Andreas",
  },
  {
    title: "Lac du Crès — insjöbad",
    description:
      "Insjö 15 min från centrum: gräsplaner, skugga, badzon med livräddare på sommaren. Lugnare och mer familjeaktigt än havet. Löprunda runt sjön ~3 km. Tram 2 + 15 min gång, snabbare med cykel.",
    category: "strand",
    tags: ["utan bil", "bad", "gratis", "picknick"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 240,
    address: "Lac du Crès, Le Crès",
    lat: 43.646,
    lng: 3.939,
    addedBy: "Andreas",
  },

  // ── Hidden gems ──
  {
    title: "Parc Zoologique de Lunaret",
    featured: true,
    description:
      "Gratis djurpark på 80 hektar, mer som en skog man strosar genom: giraffer, zebror, lejon, vargar. Serre Amazonienne (regnskogskupol) kostar ~7 €. Stängt måndagar. Skuggiga stigar, picknickbord under träden. Nära huset.",
    category: "utflykt",
    tags: ["gratis", "nära huset", "barn", "skugga"],
    budgetMin: 0,
    budgetMax: 7,
    durationMin: 180,
    address: "50 Avenue Agropolis, Montpellier",
    lat: 43.64,
    lng: 3.873,
    addedBy: "Andreas",
  },
  {
    title: "Marché des Arceaux",
    featured: true,
    description:
      "Ekologisk marknad under Saint-Clément-akveduktens bågar, tisdag- och lördagsmorgnar 7–13.30. Hundratalet producenter: ost, chark, honung, oliver, vin. Mycket få turister. Kombinera med Peyrou bredvid.",
    category: "mat",
    tags: ["utan bil", "marknad", "lokalt"],
    budgetMin: 0,
    budgetMax: 20,
    durationMin: 90,
    address: "Boulevard des Arceaux, Montpellier",
    lat: 43.611,
    lng: 3.867,
    addedBy: "Andreas",
  },
  {
    title: "Place de la Canourgue — vinpaus",
    description:
      "Ett av stans vackraste torg, gömt bakom Rue Foch: lummiga träd, enhörningsfontän, små vinbarer. Lokalbefolkningens val när Comédie blir stökigt. Bäst sen eftermiddag när skuggan kommer. Le Petit Jardin runt hörnet.",
    category: "bar",
    tags: ["utan bil", "vin", "lugnt"],
    budgetMin: 3,
    budgetMax: 15,
    durationMin: 90,
    address: "Place de la Canourgue, Montpellier",
    lat: 43.6122,
    lng: 3.8734,
    addedBy: "Andreas",
  },
  {
    title: "Place Saint-Roch & kyrkan",
    description:
      "Centralt men lugnt torg framför nygotiska Église Saint-Roch. Klassiska terrasser, en av stans bästa glassbarer nära. Kyrkan gratis och svalt vid hetta. Bra fikastopp mellan Écusson och stationen.",
    category: "annat",
    tags: ["utan bil", "fika", "glass"],
    budgetMin: 0,
    budgetMax: 6,
    durationMin: 45,
    address: "Place Saint-Roch, Montpellier",
    lat: 43.608,
    lng: 3.875,
    addedBy: "Andreas",
  },
  {
    title: "Domaine de Méric",
    description:
      "Målaren Frédéric Bazilles rosa sommarvilla, idag öppen park längs Lez: skogsstigar, ängar, picknickbord. Ofta helt tomt. Kombineras lätt med löprunda längs floden.",
    category: "utflykt",
    tags: ["gratis", "picknick", "lugnt"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 150,
    address: "Rue de Méric, Montpellier",
    lat: 43.625,
    lng: 3.885,
    addedBy: "Andreas",
  },
  {
    title: "Kanonkulan på Rue des Étuves",
    description:
      "Kuriosa: en kanonkula inkilad i fasaden på nr 30, enligt legenden från belägringen 1622. Lätt att missa — titta upp. Bra nördigt delmål på en Écusson-vandring.",
    category: "annat",
    tags: ["gratis", "kuriosa", "5 minuter"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 10,
    address: "30 Rue des Étuves, Montpellier",
    lat: 43.608,
    lng: 3.876,
    addedBy: "Andreas",
  },

  // ── Tågutflykter ──
  {
    title: "Sète — Languedocs Venedig",
    featured: true,
    description:
      "Medelhavets största franska fiskehamn med kanaler. Mont Saint-Clair för panoramautsikt, tielle (bläckfiskpaj) vid hamnen. Tåg från Saint-Roch 20 min, varje halvtimme, ingen bokning. Enklaste logistiken för 7 personer.",
    category: "utflykt",
    tags: ["tåg", "heldag", "hav", "mat"],
    budgetMin: 12,
    budgetMax: 40,
    durationMin: 480,
    address: "Sète",
    lat: 43.405,
    lng: 3.697,
    addedBy: "Andreas",
  },
  {
    title: "Nîmes — romerska ruiner",
    description:
      "En av Frankrikes bäst bevarade romerska städer: arenan från år 70, Maison Carrée (UNESCO), Jardins de la Fontaine för svalka. Tåg 30 min. Kombobiljett arena + Maison Carrée + Tour Magne. Buss 168 vidare till Pont du Gard.",
    category: "kultur",
    tags: ["tåg", "heldag", "unesco", "historia"],
    budgetMin: 16,
    budgetMax: 30,
    durationMin: 480,
    address: "Nîmes",
    lat: 43.838,
    lng: 4.36,
    addedBy: "Andreas",
  },
  {
    title: "Pont du Gard",
    featured: true,
    description:
      "2000 år gammal romersk akvedukt över Gardon, UNESCO. Gratis för fotgängare, och floden under bron är simbar — ta badkläder. Tåg till Nîmes + buss 168, ca 1 h totalt. Nîmes kan kombineras på hemvägen.",
    category: "utflykt",
    tags: ["unesco", "bad", "heldag"],
    budgetMin: 0,
    budgetMax: 20,
    durationMin: 480,
    address: "Pont du Gard, Vers-Pont-du-Gard",
    lat: 43.947,
    lng: 4.535,
    addedBy: "Andreas",
  },
  {
    title: "Aigues-Mortes — medeltidsstad & flamingos",
    description:
      "Intakt medeltida stad med 1200-talsmurar i Camargue-naturparken: rosa flamingos, vita hästar, saltsjöar. Klättra på murarna för bästa flamingovyn. Tåg ~40 min. Hela stan ses på 3–4 timmar.",
    category: "utflykt",
    tags: ["tåg", "heldag", "medeltid", "djur"],
    budgetMin: 10,
    budgetMax: 25,
    durationMin: 420,
    address: "Aigues-Mortes",
    lat: 43.567,
    lng: 4.191,
    addedBy: "Andreas",
  },
  {
    title: "Avignon — påvarnas stad",
    description:
      "Palais des Papes, 1300-talets största gotiska palats, plus halvbron Pont d'Avignon. Hela gamla stan UNESCO. Tåg ~1 h 5 min. Räkna 2+ timmar för palatset; lunch i Les Halles d'Avignon.",
    category: "kultur",
    tags: ["tåg", "heldag", "unesco"],
    budgetMin: 22,
    budgetMax: 45,
    durationMin: 540,
    address: "Avignon",
    lat: 43.949,
    lng: 4.806,
    addedBy: "Andreas",
  },

  // ── Träning ──
  {
    title: "Parc de la Rauze — utegym",
    description:
      "Stans bästa street workout, 750 m från huset: 8 moduler, ringar, höjdvarierade pull-up-stänger, parallella barr. Renoverat 2020, 4.8 på Google. Bra för intermediate–advanced kalistenik. För Leo (och Andreas).",
    category: "sport",
    tags: ["gratis", "nära huset", "utegym", "kalistenik"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 90,
    address: "Parc de la Rauze, Montpellier",
    lat: 43.594,
    lng: 3.892,
    addedBy: "Andreas",
  },
  {
    title: "Parc Georges Charpak — löprunda & utegym",
    description:
      "10 hektar park i Antigone-distriktet med mindre utegym och stora gräsytor. Bra vändpunkt för löprunda (1,5 km enkel väg); cykelvägen längs Lez börjar här. Obs: stängt helger.",
    category: "sport",
    tags: ["gratis", "löpning", "utegym"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 120,
    address: "Parc Georges Charpak, Montpellier",
    lat: 43.6,
    lng: 3.905,
    addedBy: "Andreas",
  },
  {
    title: "Löprunda längs Lez",
    description:
      "Stans bästa löprunda: cykelväg och löpstig längs Lez från Antigone ner till havet vid Palavas (10 km enkel väg, platt och delvis skuggig). Börjar 200 m från huset. För halvmaraton-passen — spring morgon eller kväll, vattenposter längs vägen.",
    category: "sport",
    tags: ["gratis", "löpning", "nära huset"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 60,
    address: "Lez-cykelvägen, Montpellier",
    lat: 43.596,
    lng: 3.901,
    addedBy: "Andreas",
  },

  // ── Bilutflykter (5 platser i bilen, 7 personer — pussel) ──
  {
    title: "Saint-Guilhem-le-Désert",
    featured: true,
    description:
      "UNESCO-by från 800-talet i Hérault-ravinen, en av Frankrikes officiellt vackraste byar. Kullerstensgränder, Abbaye de Gellone (gratis, svalt), bad vid Pont du Diable nedanför. 40 min bil; parkera vid Maison du Grand Site, gratis shuttle. Funkar för alla åldrar.",
    category: "utflykt",
    tags: ["bil", "heldag", "unesco", "bad"],
    budgetMin: 0,
    budgetMax: 35,
    durationMin: 480,
    address: "Saint-Guilhem-le-Désert",
    lat: 43.735,
    lng: 3.548,
    addedBy: "Andreas",
  },
  {
    title: "Lac du Salagou — röd insjö",
    featured: true,
    description:
      "Spektakulär insjö omgiven av röd lerjord, marslandskap-känsla. Bad, kajak, paddleboard, picknick på röda klippor. Ofta tomt jämfört med havet. 55 min bil; stränderna vid Les Vailhès bäst. Ta med picknick — få restauranger.",
    category: "strand",
    tags: ["bil", "bad", "heldag", "barn"],
    budgetMin: 0,
    budgetMax: 20,
    durationMin: 420,
    address: "Lac du Salagou, Clermont-l'Hérault",
    lat: 43.652,
    lng: 3.386,
    addedBy: "Andreas",
  },
  {
    title: "Cirque de Mourèze — månlandskap",
    description:
      "Dolomitiska kalkstenspelare som ser ut som Mars. Stigar mellan jättepelare — Elton kan klättra och utforska, vackert för vuxna. Sentier des Courtinals tar 1,5 h. Robusta skor! Kombineras lätt med Salagou samma dag.",
    category: "utflykt",
    tags: ["bil", "vandring", "barn"],
    budgetMin: 0,
    budgetMax: 0,
    durationMin: 180,
    address: "Mourèze",
    lat: 43.618,
    lng: 3.363,
    addedBy: "Andreas",
  },
  {
    title: "Bambouseraie d'Anduze — bambuskog",
    featured: true,
    description:
      "Europas enda bambuskogsträdgård (1856): 1 300 bambuvarianter, luftstig 8 m upp, laotisk by, labyrint. 35 hektar, mycket skugga — perfekt i värmen. Helt unikt för en 9-åring, roar vuxna i timmar. 1 h 5 min bil.",
    category: "utflykt",
    tags: ["bil", "barn", "skugga", "halvdag"],
    budgetMin: 10,
    budgetMax: 15,
    durationMin: 300,
    address: "Bambouseraie en Cévennes, Générargues",
    lat: 44.075,
    lng: 3.976,
    addedBy: "Andreas",
  },
  {
    title: "Cirque de Navacelles — UNESCO-canyon",
    description:
      "300 m djup canyon urgrävd av Vis, UNESCO (Causses & Cévennes). Belvédère Baume Auriol för panoramat; vandringen ner är brant — spara krafter för uppvägen (gratis sommarshuttle finns). 1 h 30 min bil. Inte för lata dagar.",
    category: "utflykt",
    tags: ["bil", "vandring", "unesco", "heldag"],
    budgetMin: 0,
    budgetMax: 5,
    durationMin: 480,
    address: "Cirque de Navacelles",
    lat: 43.893,
    lng: 3.51,
    addedBy: "Andreas",
  },
  {
    title: "Camargue & Saintes-Maries-de-la-Mer",
    description:
      "Frankrikes vildaste naturreservat: flamingos i tusental, vita hästar, svarta tjurar. Parc Ornithologique du Pont de Gau garanterar flamingos; ridturer ~25 €/h. Saintes-Maries är bohemisk fiskeby vid havet. 1 h 15 min bil; kombineras med Aigues-Mortes på hemvägen.",
    category: "utflykt",
    tags: ["bil", "djur", "heldag", "barn"],
    budgetMin: 0,
    budgetMax: 30,
    durationMin: 540,
    address: "Saintes-Maries-de-la-Mer",
    lat: 43.452,
    lng: 4.428,
    addedBy: "Andreas",
  },
  {
    title: "Cap d'Agde — vulkanstrand & Aqualand",
    description:
      "Badort med svart vulkanisk sand, Aqualand vattenpark (~30 €, kom före kl 11), marint akvarium, hyrbara motorbåtar. Mer turistigt än Palavas men fler attraktioner. 45 min bil via A9 (vägtull). Dinosaurpark i Mèze i närheten.",
    category: "strand",
    tags: ["bil", "bad", "barn", "heldag"],
    budgetMin: 0,
    budgetMax: 30,
    durationMin: 480,
    address: "Cap d'Agde",
    lat: 43.279,
    lng: 3.516,
    addedBy: "Andreas",
  },
  {
    title: "Plage de l'Espiguette — vild ödestrand",
    description:
      "18 km sanddyner utan en enda byggnad, skyddat naturreservat — öknen möter Medelhavet. Inga restauranger, ingen skugga: ta med ALLT (vatten, mat, parasoll, solskydd). Vinden kan vara stark. 1 h bil, parkering ~7 €.",
    category: "strand",
    tags: ["bil", "bad", "vilt", "heldag"],
    budgetMin: 0,
    budgetMax: 10,
    durationMin: 420,
    address: "Plage de l'Espiguette, Le Grau-du-Roi",
    lat: 43.487,
    lng: 4.143,
    addedBy: "Andreas",
  },
  {
    title: "Uzès — Frankrikes första hertigdöme",
    description:
      "Perfekt bevarad medeltidsstad med arkadtorg och slott; lördagsmarknaden är en av Frankrikes finaste. Kombinera med Pont du Gard på vägen (bada i Gardon!) — båda på en dag om man startar tidigt. 55 min bil.",
    category: "kultur",
    tags: ["bil", "marknad", "heldag"],
    budgetMin: 0,
    budgetMax: 25,
    durationMin: 480,
    address: "Uzès",
    lat: 44.012,
    lng: 4.42,
    addedBy: "Andreas",
  },
  {
    title: "Carcassonne — medeltida sagostad",
    featured: true,
    description:
      "Europas största bevarade medeltida befästa stad: 3 km dubbla murar, 52 torn, UNESCO. Som ett sagoslott — särskilt för Elton. Parkera utanför murarna och gå in för magisk första bild. Ät cassoulet. 1 h 20 min bil, avgång före kl 9.",
    category: "utflykt",
    tags: ["bil", "unesco", "medeltid", "heldag", "barn"],
    budgetMin: 0,
    budgetMax: 35,
    durationMin: 600,
    address: "Cité de Carcassonne",
    lat: 43.206,
    lng: 2.364,
    addedBy: "Andreas",
  },

  // ── Ungdomarna: William, Anna, Leja, Leo ──
  {
    title: "Kajak i Hérault-kanjonen",
    featured: true,
    description:
      "Hyr kajak vid Saint-Guilhem (Canoe Borg/Kayak Tribu, boka morgon) och paddla genom kanjonen: 200 m klippväggar, iskallt vatten, klipphopp längs vägen och flytande bar halvvägs. 4–15 km — 15 km är en riktig dag. Sätter tonen för veckan.",
    category: "sport",
    tags: ["ungdomar", "bad", "adrenalin", "boka"],
    budgetMin: 20,
    budgetMax: 30,
    durationMin: 300,
    address: "Saint-Guilhem-le-Désert",
    lat: 43.735,
    lng: 3.548,
    addedBy: "Andreas",
  },
  {
    title: "Nonna Gioia rooftop",
    featured: true,
    description:
      "Italiensk rooftop på hotell JOST: 360°-utsikt, pool, spritz (~12 €), DJ med Mediterranean house i solnedgången. 18.30 för solnedgång, 21 för DJ-set. Smart casual. Endast sommaröppet.",
    category: "bar",
    tags: ["ungdomar", "rooftop", "solnedgång", "18+"],
    budgetMin: 30,
    budgetMax: 50,
    durationMin: 180,
    address: "Hotel JOST, Montpellier",
    lat: 43.608,
    lng: 3.877,
    addedBy: "Andreas",
  },
  {
    title: "Marché du Lez",
    description:
      "Industrial-chic marknadshall vid Lez: dagtid vintage och flea market, kvällstid streetfood-paradis med fyra rooftops (Toi Toit Mon Toit asiatiskt, Coyot Bar Tex-Mex + DJs, Muchacha latin). Tram 3 till Rives du Lez.",
    category: "mat",
    tags: ["ungdomar", "streetfood", "kväll"],
    budgetMin: 20,
    budgetMax: 40,
    durationMin: 240,
    address: "1348 Avenue Raymond Dugrand, Montpellier",
    lat: 43.597,
    lng: 3.899,
    addedBy: "Andreas",
  },
  {
    title: "Söndagsbrunch på Marché du Lez",
    description:
      "Legendarisk söndagsritual 10–14: ostron, vitt vin, chark, ost, brunch-skålar, ibland liveband. Vandra mellan stånden, hitta en plats vid floden, häng 2–3 timmar. Bra start på en lugn söndag före strand eller siesta.",
    category: "mat",
    tags: ["ungdomar", "söndag", "brunch"],
    budgetMin: 15,
    budgetMax: 30,
    durationMin: 180,
    address: "Marché du Lez, Montpellier",
    lat: 43.597,
    lng: 3.899,
    addedBy: "Andreas",
  },
  {
    title: "Plage du Grand Travers",
    description:
      "8 km oexploaterad sandstrand mellan La Grande-Motte och Carnon, sanddyner istället för betong. Beach clubs Effet Mer och Le Soleil för drinkpauser; solsäng + parasoll ~15 €/halvdag. Tram 3 + buss 633.",
    category: "strand",
    tags: ["ungdomar", "bad", "utan bil"],
    budgetMin: 7,
    budgetMax: 40,
    durationMin: 360,
    address: "Plage du Grand Travers, La Grande-Motte",
    lat: 43.562,
    lng: 4.055,
    addedBy: "Andreas",
  },
  {
    title: "Rockstore & L'Antirouille — klubbkväll",
    description:
      "Rockstore: ikonisk musikhall i gammal kyrka med Cadillac över entrén, indie/rock, ons–lör 18–06. L'Antirouille: underground för techno/hip-hop/electro. Inträde 5–15 €. Obs: klubbarna fylls först efter midnatt — omkalibrera från svensk tid. 18+.",
    category: "bar",
    tags: ["ungdomar", "klubb", "livemusik", "18+"],
    budgetMin: 30,
    budgetMax: 60,
    durationMin: 360,
    address: "20 Rue de Verdun, Montpellier",
    lat: 43.607,
    lng: 3.881,
    addedBy: "Andreas",
  },
  {
    title: "Pic Saint-Loup wine tour med Bertrand Bosc",
    description:
      "Småskalig vintur (max 8 pers) i Languedocs mest respekterade region: två familjeägda vingårdar + lunch lagad av Bertrands mamma. Inte en turistgrej — en söndag i Languedoc med en familj som bor där. Bokas via Viator/GetYourGuide. 18+ för provningen.",
    category: "bar",
    tags: ["vin", "boka", "18+", "halvdag"],
    budgetMin: 70,
    budgetMax: 100,
    durationMin: 360,
    address: "Pic Saint-Loup (avgång Boulevard Sarrail)",
    lat: 43.78,
    lng: 3.81,
    addedBy: "Andreas",
  },
  {
    title: "Pont du Diable — klippdyk & bad",
    description:
      "UNESCO-listad medeltida bro över Hérault där hela kanjonen är simbar. Klipphopp 3–8 m, djupt och iskallt vatten. Tram 1 till Mosson + buss 668 (går söndagar sommartid), 6 € t/r. Ta matsäck — lite skugga. Saint-Guilhem 10 min bort.",
    category: "strand",
    tags: ["ungdomar", "bad", "gratis", "utan bil"],
    budgetMin: 6,
    budgetMax: 10,
    durationMin: 360,
    address: "Pont du Diable, Aniane",
    lat: 43.71,
    lng: 3.556,
    addedBy: "Andreas",
  },
  {
    title: "La Dune Club, La Grande-Motte",
    description:
      "Sydfrankrikes legendariska beach club sedan 90-talet — världs-DJs (Eric Prydz, Justice m.fl.) roterar under säsongen. Stranddansgolv tills solen går upp. Kolla line-upen när ni är där; förköp online. Hemresa = taxi (~30 €). 18+.",
    category: "bar",
    tags: ["ungdomar", "klubb", "18+", "boka"],
    budgetMin: 60,
    budgetMax: 100,
    durationMin: 420,
    address: "La Grande-Motte",
    lat: 43.56,
    lng: 4.084,
    addedBy: "Andreas",
  },
  {
    title: "Cykla Lez-vägen till havet",
    description:
      "Hyr Vélomagg (7-dagarspass ~7 €!) och cykla 10 km längs Lez ner till Palavas, Carnon eller Grand Travers. Platt, asfalterat, mest skuggigt. Paus vid Domaine de Méric; solnedgång hem genom vinodlingar, middag i Antigone.",
    category: "sport",
    tags: ["cykel", "billigt", "solnedgång", "hav"],
    budgetMin: 1,
    budgetMax: 10,
    durationMin: 240,
    address: "Lez-cykelvägen, Montpellier",
    lat: 43.596,
    lng: 3.901,
    addedBy: "Andreas",
  },

  // ── Elin 50 — söndag 12 juli ──
  {
    title: "Sängfrukost för Elin (12 juli)",
    description:
      "Croissanter och pain au chocolat hämtas tidigt (William/Leja), brioche, kaviar/lax, getost från Halles Castellane, fikon, färskpressad juice, Crémant de Limoux. Bricka plockas tyst 08.00, sång 08.30. Kort, kärleksfullt, inte utdraget. Inköp görs lördag 11 juli.",
    category: "mat",
    tags: ["elin 50", "hemma", "födelsedag"],
    budgetMin: 10,
    budgetMax: 20,
    durationMin: 60,
    address: "12 Rue Nicolas Copernic, 34000 Montpellier",
    lat: 43.5951,
    lng: 3.8991,
    addedBy: "Andreas",
  },
  {
    title: "Trerätters födelsedagsmiddag hemma (12 juli)",
    description:
      "Mat som lagar sig själv — ingen står i köket: tomatsallad med burrata (5 min montering, Picpoul de Pinet), långkokt lammbog med ratatouille (in i ugnen kl 14, 140° i 4–5 h, Pic Saint-Loup röd), vacherin glacé med sommarbär från frysen (görs dagen innan). Fem stora ljus.",
    category: "mat",
    tags: ["elin 50", "hemma", "födelsedag", "förbered dagen innan"],
    budgetMin: 15,
    budgetMax: 30,
    durationMin: 180,
    address: "12 Rue Nicolas Copernic, 34000 Montpellier",
    lat: 43.5951,
    lng: 3.8991,
    addedBy: "Andreas",
  },
];
